name = "Hyde-RTL"
license = "MIT"
licenselink = "https://github.com/amrgharbeia/hyde/blob/master/LICENSE.md"
description = "An elegant open source and mobile first theme"
tags = ["blog", "company"]
features = ["blog", "themes", "disqus"]
min_version = 0.20

[author]
    name = "gharbeia"
    homepage = "https://gharbeia.net"

# If Porting existing theme
[original]
    author =  "mdo"
    homepage = "http://markdotto.com/"
    repo = "https://www.github.com/mdo/hyde"
